# Generated by Django 5.1.4 on 2025-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_friendship_unique_together_user_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default/profile.jpg', max_length=255, null=True, upload_to='profile/'),
        ),
    ]
